export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const ADD_QUANT = 'ADD_QUANT';
export const REMOVE_QUANT = 'REMOVE_QUANT';
export const DYNAMIC_QUANT = 'DYNAMIC_QUANT';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';

